#![feature(test)]

extern crate test;

#[test]
fn top_level() {}

#[test]
#[ignore]
fn ignored_without_message() {}

#[test]
#[ignore = "not ready yet"]
fn ignored_with_message() {}

#[test]
#[should_panic]
fn panics() {
    panic!()
}

#[test]
#[should_panic(expected = "boom")]
fn panics_with_message() {
    panic!("boom")
}

#[bench]
fn a_benchmark(b: &mut test::Bencher) {
    b.iter(|| 1 + 1);
}

mod zzz_last_module {
    #[test]
    fn sorts_after_nested() {}
}

mod nested {
    #[test]
    fn shallow() {}

    pub mod deeper {
        #[test]
        fn deep() {}

        #[test]
        #[should_panic(expected = "quoted \" backslash \\ newline")]
        fn needs_json_escaping() {
            panic!("quoted \" backslash \\ newline")
        }
    }
}

// A test generated by a macro still ends up in the harness, so it must show up
// in the dump too.
macro_rules! make_test {
    ($name:ident) => {
        #[test]
        fn $name() {}
    };
}
make_test!(from_a_macro);
